### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by wonAdam** [cheolhakja/cpp-movie-app#1]
안녕하세요! 홍대컴공 4학년 재학중인 사람이에요!

에타에 올리신거 보고 심심할때 코드를 잠깐 봤어요!

제 빈약한 역량이지만, 조금 개선할 여지가 보여서 남겨요!

### 1. main.cpp에 MovieBook를 스택변수로 해도 될것같아요!
C++를 공부하실 때 포인터가 아주 위험한거라는것은 느끼셨을거에요!
그래서 제가 봤을때는 최대한 힙변수는 줄이는게 좋아보여요!
`MovieBook movieBookObj;`로 스택변수로 선언하고
`movieBookObj.start();` 만 하셔도 될것같습니다!

### 2. Seat.h 에 Setter와 Getter를 두고 멤버변수들은 private으로 캡슐화시키는 것은 어떨까요?
제목 그대로 setter함수를 두실거면 멤버변수를 private으로 은닉하는 것이 좋아요!
아니면 setter를 없애고 그냥 public 멤버변수를 접근하는 방법도 있어요! 
둘중에 하나로 가시는게 좋을것같아요!

### 3. MovieBook.cpp의 start함수가 너무 비대한것같아요!
if문으로 잘 나눠놓으셨으니 if문별로 함수로 나눠보는 것이 좋을것같아요!

우선 보이는 것은 이정도일거같아요!
제가 전부 본것도 아니고 고작 4학년뽀시래기이니, 참고만 하시구요!

윤객체 수강하시느라 고생하셨어요! 앞으로도 화이팅하세요!

**Comment by wonAdam** [comment]
다쓰고나서 자바로 다시만드시는걸봤네여 -_-;;

**Comment by cheolhakja** [comment]
아 동현님 안녕하세요!! 메일을 이제서야 봤습니다 죄송합니다!!,,,,,,, 피드백 정말정말 감사합니다 ㅠㅠ,,,꼼꼼히 읽어보겠습니다
정말 감사드립니다!!....

2021년 7월 25일 일요일, 원동현 ***@***.***>님이 작성:

**Comment by cheolhakja** [comment]
앗 깃허브에 이슈라는  기능도 있었네요ㅠㅠㅠㅠ.....이제 알았습니다....ㅠ

**Comment by cheolhakja** [comment]
> 다쓰고나서 자바로 다시만드시는걸봤네여 -_-;;

**Comment by cheolhakja** [comment]
아 동현님 안녕하세요!! 메일을 이제서야 봤습니다 죄송합니다!!,,,,,,, 피드백 정말정말 감사합니다 ㅠㅠ,,,꼼꼼히 읽어보겠습니다
정말 감사드립니다!!....

**Comment by wonAdam** [comment]
@cheolhakja 
아 아닙니다! 
혹시 제 설명이 부족해서 이해가 안 가시거나 
다른 궁금한 점 있으면 말씀해주세요!
다른 질문도 환영이에요! ㅎㅎ 수고하세연

**Comment by cheolhakja** [comment]
넵 앞으로 프로그래밍할때 써주신내용이랑 클린코드, 단위테스트등을 좀더 고민하면서 코딩하려고합니다ㅎ......
